name: Run Code Daily

on:
  schedule:
    - cron: '0 5 * * *'  # 5:00 AM UTC daily
  workflow_dispatch:      # Manual trigger

jobs:
  run-daily:
    runs-on: ubuntu-latest

    env:
      PEXELKEY: ${{ secrets.PEXELKEY }}
      cloudname: ${{ secrets.cloudname }}
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      api_KEY_youtube: ${{ secrets.api_KEY_youtube }}
      client_id_youtube: ${{ secrets.client_id_youtube }}
      client_secret_youtube: ${{ secrets.client_secret_youtube }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow committing back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python youtube.py

      - name: Commit and push updated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update via GitHub Actions"
          git push
