name: Run Code Daily

on:
  schedule:
    - cron: '0 5 * * *'  # 5:00 AM UTC daily
  workflow_dispatch:      # Manual trigger

jobs:
  run-daily:
    runs-on: ubuntu-latest

    env:
      PEXELKEY: ${{ secrets.PEXELKEY }}
      cloudname: ${{ secrets.cloudname }}
      APIKEY: ${{ secrets.APIKEY }}
      APISECRET: ${{ secrets.APISECRET }}
      api_KEY_youtube: ${{ secrets.api_KEY_youtube }}
      client_id_youtube: ${{ secrets.client_id_youtube }}
      client_secret_youtube: ${{ secrets.client_secret_youtube }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug — Show directory contents before running script
        run: |
          echo "Current directory:"
          pwd
          echo "Files:"
          dir

      - name: Run script
        run: |
          python youtube.py

      - name: Debug — Show files after running script
        run: |
          echo "Files after script run:"
          dir

      - name: Upload video artifacts (for debugging)
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: |
            /temp/final_video.mp4
            /temp/transformed_video.mp4

      - name: List all files after script
        run: dir
