name: YT Analysis

on:
#  schedule:
#    - cron: '0 13 * * *'  # 5:00 AM UTC daily
  workflow_dispatch:      # Manual trigger

jobs:
  run-daily:
    runs-on: ubuntu-latest

    env:
      YTA_YOUTUBE_REFRESH_TOKEN: ${{ secrets.YTA_YOUTUBE_REFRESH_TOKEN }}
      GSHEETS_REFRESH_TOKEN: ${{ secrets.GSHEETS_REFRESH_TOKEN }}
      YTA_CLIENT_ID: ${{ secrets.YTA_CLIENT_ID }}
      YTA_CLIENT_SECRET: ${{ secrets.YTA_CLIENT_SECRET }}
      channel_id: ${{ secrets.CHANNEL_ID }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Allow committing back

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          python youtube_analysis.py

